[package]
name = "gnome-twitter"
version = "0.1.0"
authors = ["Adam Saladino <adam@codingsimply.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[dependencies.gtk]
version = "0.6.0"
features = ["v3_16"]